services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
      POSTGRES_DB: payload
    ports:
      - "5433:5432"
    volumes:
      - jw-postgres-data:/var/lib/postgresql/data

volumes:
  jw-postgres-data:
