/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    testimonials: Testimonial;
    'faq-items': FaqItem;
    'photo-categories': PhotoCategory;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'faq-items': FaqItemsSelect<false> | FaqItemsSelect<true>;
    'photo-categories': PhotoCategoriesSelect<false> | PhotoCategoriesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'photography-page': PhotographyPage;
    'faq-page': FaqPage;
    'contact-page': ContactPage;
    'impressum-page': ImpressumPage;
    'datenschutz-page': DatenschutzPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'photography-page': PhotographyPageSelect<false> | PhotographyPageSelect<true>;
    'faq-page': FaqPageSelect<false> | FaqPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'impressum-page': ImpressumPageSelect<false> | ImpressumPageSelect<true>;
    'datenschutz-page': DatenschutzPageSelect<false> | DatenschutzPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt-Text für Screenreader/SEO — kurz beschreiben, was im Bild passiert.
   */
  alt: string;
  blurDataURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  author: string;
  /**
   * Reihenfolge im Karussell, aufsteigend.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items".
 */
export interface FaqItem {
  id: number;
  question: string;
  answer: string;
  /**
   * Reihenfolge auf der Seite, aufsteigend.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-categories".
 */
export interface PhotoCategory {
  id: number;
  /**
   * Interner Schlüssel, z. B. "familie".
   */
  slug: string;
  eyebrow: string;
  headline: string;
  text: string;
  /**
   * Slides des Kategorie-Karussells, in Anzeigereihenfolge.
   */
  images: (number | Media)[];
  /**
   * Reihenfolge auf der Seite, aufsteigend.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  occasion: string;
  message: string;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faq-items';
        value: number | FaqItem;
      } | null)
    | ({
        relationTo: 'photo-categories';
        value: number | PhotoCategory;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blurDataURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-categories_select".
 */
export interface PhotoCategoriesSelect<T extends boolean = true> {
  slug?: T;
  eyebrow?: T;
  headline?: T;
  text?: T;
  images?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  occasion?: T;
  message?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  logo: {
    top: string;
    bottom: string;
    /**
     * Logo-Datei (PNG, randlos beschnitten).
     */
    image?: (number | null) | Media;
  };
  nav: {
    label: string;
    href: string;
    id?: string | null;
  }[];
  footer: {
    name: string;
    tagline: string;
    quote: string;
    links: {
      label: string;
      href: string;
      id?: string | null;
    }[];
    copyright: string;
  };
  instagram: {
    handle: string;
    url: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  meta: {
    title: string;
    description: string;
  };
  /**
   * Slides des Hero-Karussells auf der Startseite.
   */
  heroSlides: {
    image: number | Media;
    id?: string | null;
  }[];
  hero: {
    title: string;
    subtitle: string;
  };
  intro: {
    /**
     * Genau *einen* Teil in Sternchen setzen — wird kursiv/gold hervorgehoben.
     */
    headline: string;
    /**
     * Mobile Variante — \n erzwingt einen Zeilenumbruch.
     */
    headlineMobile: string;
    paragraphs: {
      text: string;
      id?: string | null;
    }[];
    buttonLabel: string;
    buttonHref: string;
    portraitImage: number | Media;
    polaroidImage: number | Media;
    stickerLabel: string;
  };
  marqueeItems: {
    text: string;
    id?: string | null;
  }[];
  services: {
    /**
     * Genau *einen* Teil in Sternchen setzen — wird kursiv/gold hervorgehoben.
     */
    headline: string;
    subline: string;
    cards: {
      title: string;
      text: string;
      image: number | Media;
      id?: string | null;
    }[];
    buttonLabel: string;
    buttonHref: string;
  };
  works: {
    /**
     * Genau *einen* Teil in Sternchen setzen — wird kursiv/gold hervorgehoben.
     */
    headline: string;
    text: string;
    images: (number | Media)[];
    buttonLabel: string;
    buttonHref: string;
  };
  testimonials: {
    headline: string;
  };
  trust: {
    instagramTextBefore: string;
    googleStarsLine: string;
    reviewButtonLabel: string;
    reviewUrl: string;
  };
  cta: {
    /**
     * Genau *einen* Teil in Sternchen setzen — wird kursiv/gold hervorgehoben.
     */
    headline: string;
    text?: string | null;
    buttonLabel: string;
    buttonHref: string;
    quote?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  meta: {
    title: string;
    description: string;
  };
  /**
   * Genau *einen* Teil in Sternchen setzen — wird kursiv/gold hervorgehoben.
   */
  headline: string;
  marqueeItems: {
    text: string;
    id?: string | null;
  }[];
  intro: {
    portraitImage: number | Media;
    headline: string;
    paragraphs: {
      text: string;
      id?: string | null;
    }[];
  };
  passion: {
    headline: string;
    paragraphs: {
      text: string;
      id?: string | null;
    }[];
    image: number | Media;
  };
  facts: {
    /**
     * Genau *einen* Teil in Sternchen setzen — wird kursiv/gold hervorgehoben.
     */
    headline: string;
    items: {
      text: string;
      id?: string | null;
    }[];
  };
  cta: {
    /**
     * Genau *einen* Teil in Sternchen setzen — wird kursiv/gold hervorgehoben.
     */
    headline: string;
    text?: string | null;
    buttonLabel: string;
    buttonHref: string;
    quote?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photography-page".
 */
export interface PhotographyPage {
  id: number;
  meta: {
    title: string;
    description: string;
  };
  /**
   * Genau *einen* Teil in Sternchen setzen — wird kursiv/gold hervorgehoben.
   */
  headline: string;
  marqueeItems: {
    text: string;
    id?: string | null;
  }[];
  cta: {
    /**
     * Genau *einen* Teil in Sternchen setzen — wird kursiv/gold hervorgehoben.
     */
    headline: string;
    text?: string | null;
    buttonLabel: string;
    buttonHref: string;
    quote?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page".
 */
export interface FaqPage {
  id: number;
  meta: {
    title: string;
    description: string;
  };
  /**
   * Genau *einen* Teil in Sternchen setzen — wird kursiv/gold hervorgehoben.
   */
  headline: string;
  marqueeItems: {
    text: string;
    id?: string | null;
  }[];
  cta: {
    /**
     * Genau *einen* Teil in Sternchen setzen — wird kursiv/gold hervorgehoben.
     */
    headline: string;
    text?: string | null;
    buttonLabel: string;
    buttonHref: string;
    quote?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  meta: {
    title: string;
    description: string;
  };
  /**
   * Genau *einen* Teil in Sternchen setzen — wird kursiv/gold hervorgehoben.
   */
  headline: string;
  intro: string;
  form: {
    nameLabel: string;
    emailLabel: string;
    phoneLabel: string;
    occasionLabel: string;
    messageLabel: string;
    sourceQuestion: string;
    /**
     * Auswahl-Chips "Wie hast du mich gefunden?"
     */
    sources: {
      text: string;
      id?: string | null;
    }[];
    consentText: string;
    submitLabel: string;
  };
  side: {
    portraitImage: number | Media;
    stickerLabel: string;
    headline: string;
    instagramTextBefore: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impressum-page".
 */
export interface ImpressumPage {
  id: number;
  meta: {
    title: string;
    description: string;
  };
  headline: string;
  /**
   * TODO: echten Rechtstext eintragen (z. B. per e-recht24.de-Generator).
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datenschutz-page".
 */
export interface DatenschutzPage {
  id: number;
  meta: {
    title: string;
    description: string;
  };
  headline: string;
  /**
   * TODO: echten Rechtstext eintragen (z. B. per e-recht24.de-Generator).
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?:
    | T
    | {
        top?: T;
        bottom?: T;
        image?: T;
      };
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        name?: T;
        tagline?: T;
        quote?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        copyright?: T;
      };
  instagram?:
    | T
    | {
        handle?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  heroSlides?:
    | T
    | {
        image?: T;
        id?: T;
      };
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  intro?:
    | T
    | {
        headline?: T;
        headlineMobile?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        buttonLabel?: T;
        buttonHref?: T;
        portraitImage?: T;
        polaroidImage?: T;
        stickerLabel?: T;
      };
  marqueeItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  services?:
    | T
    | {
        headline?: T;
        subline?: T;
        cards?:
          | T
          | {
              title?: T;
              text?: T;
              image?: T;
              id?: T;
            };
        buttonLabel?: T;
        buttonHref?: T;
      };
  works?:
    | T
    | {
        headline?: T;
        text?: T;
        images?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  testimonials?:
    | T
    | {
        headline?: T;
      };
  trust?:
    | T
    | {
        instagramTextBefore?: T;
        googleStarsLine?: T;
        reviewButtonLabel?: T;
        reviewUrl?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        text?: T;
        buttonLabel?: T;
        buttonHref?: T;
        quote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  headline?: T;
  marqueeItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  intro?:
    | T
    | {
        portraitImage?: T;
        headline?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  passion?:
    | T
    | {
        headline?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
      };
  facts?:
    | T
    | {
        headline?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        headline?: T;
        text?: T;
        buttonLabel?: T;
        buttonHref?: T;
        quote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photography-page_select".
 */
export interface PhotographyPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  headline?: T;
  marqueeItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        text?: T;
        buttonLabel?: T;
        buttonHref?: T;
        quote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page_select".
 */
export interface FaqPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  headline?: T;
  marqueeItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        text?: T;
        buttonLabel?: T;
        buttonHref?: T;
        quote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  headline?: T;
  intro?: T;
  form?:
    | T
    | {
        nameLabel?: T;
        emailLabel?: T;
        phoneLabel?: T;
        occasionLabel?: T;
        messageLabel?: T;
        sourceQuestion?: T;
        sources?:
          | T
          | {
              text?: T;
              id?: T;
            };
        consentText?: T;
        submitLabel?: T;
      };
  side?:
    | T
    | {
        portraitImage?: T;
        stickerLabel?: T;
        headline?: T;
        instagramTextBefore?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impressum-page_select".
 */
export interface ImpressumPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  headline?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datenschutz-page_select".
 */
export interface DatenschutzPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  headline?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}